name: aided_driving_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  uuid: ^2.0.0
  shared_preferences: ^0.5.1+1
  json_annotation: ^2.0.0
  local_auth: ^0.4.0+1
  native_widgets: ^1.0.1
  get_version: ^0.0.8+5
  flutter_whatsnew: ^0.2.0+3
  persist_theme: ^0.0.3+6
  http: ^0.12.0+1
  flutter_inner_drawer: ^0.2.5
  fancy_bottom_navigation: ^0.3.2
  animated_floatactionbuttons: ^0.1.0
  shifting_tabbar: ^0.3.1
  flutter_slidable: ^0.4.9
  flutter_sequence_animation: ^3.0.0
  share: ^0.6.0+1
  url_launcher: ^4.0.2
  charts_flutter: ^0.6.0
  flutter_circular_slider: ^1.1.4
  tts: ^1.0.2
  loading_view: ^1.0.2
  intro_views_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/images/about_logo.png
  - assets/images/icon_notify_done.png
  - assets/images/icon_notify_error.png
  - assets/images/icon_notify_info.png
  - assets/images/air-hostess.png
  - assets/images/airplane.png
  - assets/images/bus-driver.png
  - assets/images/bus.png
  - assets/images/hotel.png
  - assets/images/taxi.png
  - assets/images/taxi-driver.png
  - assets/images/waiter.png
  - assets/images/identify_personal.png
  - assets/images/identify_enterprise.png
  - assets/images/identify_developer.png
  - resources/lang/
#  - assets/images/launch_image.jpg
  #  - assets/images/person.jpg
  #  - assets/images/login_logo.png
  #  - assets/images/header.jpg
  #  - assets/images/body.jpg
  #  - assets/images/profile_header_background.png
  #  - assets/images/portfolio_1.jpeg
  #  - assets/images/portfolio_2.jpeg
  #  - assets/images/portfolio_3.jpeg
  #  - assets/images/portfolio_4.jpeg
  #  - assets/images/portfolio_5.jpeg
  #  - assets/images/portfolio_6.jpeg
  #  - assets/images/place_holder.jpg
  #  - assets/images/place_holder_2.jpg
  #  - assets/images/place_holder_3.jpg
  #  - resources/lang/ch.json
  #  - resources/lang/en.json
  #  - resources/lang/pt.json

  fonts:
  - family: WorkSansSemiBold
    fonts:
    - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

  - family: WorkSansBold
    fonts:
    - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

  - family: WorkSansMedium
    fonts:
    - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

  - family: MyFont
    fonts:
    - asset: assets/Fonts/sspu.ttf